name: FunctionalDesignDocumentToTechnicalDesignDocument
description: Generate Technical Design Document (TDD) JSON from FDD using MCP and repository rules

capabilities:
  tools:
    - http

instructions:

  # 1. Extract Work Item ID
  - step: extract_input
    description: |
      Extract the numeric Work Item ID from the user prompt.
      The work item always belongs to Azure DevOps.
    output: workItemId

  # 2. Fetch FDD from MCP
  - step: fetch_fdd
    description: |
      Fetch Functional Design Document (FDD) content using the MCP Azure Function.
      This is the ONLY allowed source of FDD data.
    tool: http
    method: GET
    url: https://devcopilotmcp-esceawhsbvekgwgu.eastus2-01.azurewebsites.net/api/fdd/{workItemId}?code=aHEE39eovMNux1zFkGLO6OhPvxuJmi_KcH4XWzzbN3BgAzFu_X4uNg==
    responseVariable: FDDContent

  # 3. Generate TDD JSON (FORCED CONTEXT)
  - step: generate_tdd
    description: |
      You are generating a Technical Design Document (TDD).

      ===============================
      FUNCTIONAL DESIGN DOCUMENT (FDD)
      ===============================
      The following JSON is the complete and authoritative FDD.
      You MUST use ONLY this content.

      {{FDDContent}}

      ===============================
      END OF FDD
      ===============================

      ## Locked Rules (NON-NEGOTIABLE)
      - Do NOT attempt to locate the work item elsewhere.
      - Do NOT ask for URLs, repositories, or links.
      - Do NOT ask clarifying questions.
      - Do NOT request templates or formats.
      - The FDD above is complete and sufficient.

      ## Authoritative References
      - Repository knowledge:
        - .knowledge/technical-standards.md
      - System rules:
        - .prompts/FDD2TDDSystemMessage.md
      - Output schema:
        - .schemas/sample-tdd-structure.json

      ## Output Rules
      - Output strictly valid JSON.
      - Follow the schema exactly.
      - Do NOT invent data.
      - If something is missing, use null or empty arrays.
      - No markdown.
      - No explanations.
      - No comments.
      - No questions.

output:
  format: json
