capabilities:
  tools:
    - http

instructions:
  - step: extract_input
    description: Extract Work Item ID
    output: workItemId

  - step: fetch_fdd
    tool: http
    method: GET
    url: https://devcopilotmcp-esceawhsbvekgwgu.eastus2-01.azurewebsites.net/api/fdd/325423?code=aHEE39eovMNux1zFkGLO6OhPvxuJmi_KcH4XWzzbN3BgAzFu_X4uNg==
    responseVariable: FDDContent

  - step: generate_tdd
    description: |
      Generate TDD JSON using FDDContent
