name: FDD-to-TDD-Agent
description: Converts FDD content to structured TDD JSON

instructions:
  - Call the API to fetch FDD content before processing:
      method: GET
      url: http://localhost:7088/api/getWorkitem/1188489
      responseVariable: FDDContent

  - Use the fetched FDDContent as the primary input.

  - Follow the rules, structure, and generation logic defined in:
      promptFile: .prompts/FDD2TDDSystemMessage.md

  - Generate the output strictly as TDD JSON as specified in the prompt file.

capabilities:
  tools:
    - http

context:
  inputs:
    - FDDContent
